MvcTiendaPrueba/Controllers/TiendaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MvcTiendaPrueba.Extensions;
using MvcTiendaPrueba.Models;
using MvcTiendaPrueba.Services;

namespace MvcTiendaPrueba.Controllers
{
    public class TiendaController : Controller
    {
        private ServiceApiTienda service;
        private ServiceCacheRedis cacheredis;
        private IHttpContextAccessor httpContextAccessor;
        public TiendaController(ServiceApiTienda service, ServiceCacheRedis cacheredis, IHttpContextAccessor httpContextAccessor)
        {
            this.service = service;
            this.cacheredis = cacheredis;
            this.httpContextAccessor = httpContextAccessor;
        }

        public async Task<IActionResult> Index()
        {
            var categorias = await service.GetCategoriasAsync();
            ViewData["CATEGORIAS"] = categorias;
            var comentarios = service.GetComentariosAsync();
            ViewData["COMENTARIOS"] = comentarios;
            return View();
        }


        /*******************************/

        public async Task<IActionResult> DetailsProducto
            (int idproducto)
        {
            List<Comentario> comentarios = await this.service.FindComentariosAsync(idproducto);
            HttpContext.Session.SetObject("COMENTARIOS", comentarios);

            Producto producto = await this.service.FindProductosAsync(idproducto);
            return View(producto);
        }

        public async Task<IActionResult> PaginarGrupoProductos(int? posicion)
        {
            var categorias = await service.GetCategoriasAsync();
            ViewData["CATEGORIAS"] = categorias;
            if (posicion == null)
            {
                posicion = 1;
            }
            int registros = await this.service.GetNumeroProductosAsync();
            List<Producto> productos = await this.service.GetGrupoProductosAsync(posicion.Value);
            ViewData["REGISTROS"] = registros;
            ViewData["NumeroPaginaActual"] = posicion; // Pasa el número de página actual a la vista
            return View(productos);
        }

        public async Task<IActionResult> ProductosCategoria(int? posicion, int idcategoria)
        {
            var categorias = await service.GetCategoriasAsync();
            ViewData["CATEGORIAS"] = categorias;
            if (posicion == null)
            {
                posicion = 1;
            }
           
                List<Producto> productos = await this.service.GetGrupoProductosCategoriaAsync(posicion.Value,idcategoria);
                int registros = await this.service.GetNumeroProductosCategoriaAsync(idcategoria);
                ViewData["REGISTROS"] = registros;
                ViewData["IDCATEGORIA"] = idcategoria;
                ViewData["NumeroPaginaActual"] = posicion; // Pasa el número de página actual a la vista
                return View(productos);
        }


        public async Task<IActionResult> Categorias()
        {
            List<Categoria> categorias = await this.service.GetCategoriasAsync();
            return View(categorias);
        }

        /************************CESTA*****************************************/

        public async Task<IActionResult> Cesta()
        {
            List<Producto> productos = await this.cacheredis.GetProductosCarritoAsync();
            return View(productos);
        }

        public async Task<IActionResult> AnyadirProductoCesta(int idproducto)
        {
            Producto producto = await this.service.FindProductosAsync(idproducto);
            await this.cacheredis.AddProductoCarritoAsync(producto);
            return RedirectToAction("PaginarGrupoProductos");

        }

        public async Task<IActionResult> EliminarProductoCesta(int idproducto)
        {
            await this.cacheredis.DeleteProductoCarritoAsync(idproducto);
            return RedirectToAction("CESTA");
        }


        /**************************FAVORITOS***************************************/

        public async Task<IActionResult> Favoritos()
        {
            List<Producto> productos = await this.cacheredis.GetProductosFavoritosAsync();
            return View(productos);
        }


        public async Task<IActionResult>
            AnyadirProductoFavoritos(int idproducto)
        {
            Producto producto = await this.service.FindProductosAsync(idproducto);
            await this.cacheredis.AddProductoFavoritoAsync(producto);
            return RedirectToAction("PAginarGrupoProductos");

        }

        public async Task<IActionResult> EliminarProductoFavoritos(int idproducto)
        {
            await this.cacheredis.DeleteProductoFavoritoAsync(idproducto);
            return RedirectToAction("FAVORITOS");
        }


        /******************** PEDIDOS ****************************/

        public async Task<IActionResult> RealizarCompra()
        {
            if (httpContextAccessor.HttpContext.User.Identity.IsAuthenticated)
            {
                Usuario usuario = await this.service.GetPerfilUsuarioAsync();
                List<Producto> productosEnCesta = await this.cacheredis.GetProductosCarritoAsync();

                // Creamos el pedido
                Pedido pedido = await this.service.CreatePedidoAsync(usuario.IdUsuario, productosEnCesta);

                // Limpiamos la cesta después de crear el pedido

                foreach (Producto producto in productosEnCesta)
                {
                    await this.cacheredis.DeleteProductoCarritoAsync(producto.IdProducto);
                }
                productosEnCesta.Clear();
            }
            return RedirectToAction("PaginarGrupoProductos");

        }
        
        public async Task<IActionResult> PedidosUsuario()
        {
            if (httpContextAccessor.HttpContext.User.Identity.IsAuthenticated)
            {
                Usuario usuario = await this.service.GetPerfilUsuarioAsync();
                List<DetallePedidoView> pedidosUsuarios = await this.service.GetProductosPedidoUsuarioAsync(usuario.IdUsuario);
                return View(pedidosUsuarios);
            }
            else
            {
                return View(new List<DetallePedidoView>());
            }
        }

    }
}

MvcTiendaPrueba/Views/Tienda/Cesta.cshtml
@model List<Producto>

<head>
    <!-- Font Awesome Icon Library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/misestilos.css" asp-append-version="true" />

</head>

<a asp-controller="Tienda" asp-action="PaginarGrupoProductos" style="margin:auto">
    <span class="material-symbols-outlined" style="color: black; border: 1px solid black; border-radius: 20px;">
        arrow_back
    </span>
</a>

<body>


    @if (Model == null)
    {
        <h2 class="text-danger" style="text-align: center;">No hay productos en tu carrito</h2>
    }
    else
    {
        <div style="display: flex; align-items: center; justify-content: space-between;margin: 1px 20px 1px 20px;">
            <h3 class="text-primary mt-3">Productos en carrito: @Model.Count()</h3>
            <h3 class="text-success mt-2">Precio total: @Model.Sum(c => c.Precio)€</h3>
        </div>

        <div class="container mt-5">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-1 g-2">
                @foreach (Producto pro in Model)
                {
                    <div class="col">
                        <div class="card shadow-sm" style="border-radius: 35px; margin-bottom:1rem;">
                            <div class="d-flex justify-content-between align-items-center card-body">
                                <img src="~/images/cenicero.png" style="width: 9%;margin-left: 30px;">
                                <div>
                                    <h4 class="card-title" style="font-weight: bold;">@pro.Nombre</h4>
                                    <p class="card-text">@pro.Descripcion</p>
                                </div>
                                <div class="ml-auto">
                                    <p style="font-weight: bold;">@pro.Precio €</p>
                                </div>
                                <div style="margin-right: 25px">
                                    <a asp-controller="Tienda" asp-action="EliminarProductoCesta"
                                       asp-route-idproducto="@pro.IdProducto" class="btn btn-danger">
                                        <span class="material-symbols-outlined">delete</span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>



        <a asp-controller="Tienda" asp-action="RealizarCompra"
           class="btn btn-success w-100 mt-3">
            Realizar compra
        </a>
    }

</body>


@section scripts {
    <script>

    </script>
}

MvcTiendaPrueba/Views/Tienda/DetailsProducto.cshtml
@model Producto

@{
    List<int> cesta = Context.Session.GetObject<List<int>>("CESTA");
    List<int> favoritos = Context.Session.GetObject<List<int>>("FAVORITOS");
    List<Comentario> comentarios = Context.Session.GetObject<List<Comentario>>("COMENTARIOS");
    string? user = Context.Session.GetString("USUARIO");

}

<head>
    <link rel="stylesheet" href="~/css/misestilos.css" asp-append-version="true" />
    <!-- Font Awesome Icon Library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <style>
        .checked {
            color: orange;
        }

        footer {
            margin-top: auto; /* Hace que el pie de página se pegue al final del contenedor */
        }
    </style>
</head>
<body style="margin-top: 60px;margin-bottom: 20px">
    <a asp-controller="Tienda" asp-action="ProductosCategoria" asp-route-idcategoria="@Model.IdCategoria" style="margin:auto">
        <span class="material-symbols-outlined" style="color: black; border: 1px solid black; border-radius: 20px;">
            arrow_back
        </span>
    </a>
    
    <ul class="services" >
        <li class="card-large card-dark card-wide" id="serv-groom">
            <div class="card-image"><img src="~/images/cenicero.png"></div>
            <ul>
                @Model.Nombre
                <span class="subtitle">@Model.Descripcion</span>
                <li><a href="#">Precio: </a><span>@Model.Precio</span></li>
                <div>
                    @if (!Context.User.Identity.IsAuthenticated)
                    {
                        <a class="btn w-100" style="background-color: #9acb8d;" href="~/Account/Login">Iniciar sesión para añadir al carrito</a>
                        <a class="btn w-100" style="background-color: #9acb8d;" href="~/Account/Login">Iniciar sesión para añadir a favoritos</a>
                    }
                    else
                    {
                        @if (cesta != null)
                        {
                            @if (!cesta.Contains(@Model.IdProducto))
                            {
                                <a asp-controller="Tienda"
                                   asp-action="AnyadirProductoCesta"
                                   asp-route-idproducto="@Model.IdProducto"
                                   class="btn w-100" style="background-color: #9acb8d;">
                                    Añadir producto a carrito
                                </a>
                            }
                            else
                            {
                                <button class="btn btn-secondary w-100">
                                    Producto ya en la cesta
                                </button>
                            }
                        }
                        else
                        {
                            <a asp-controller="Tienda"
                               asp-action="AnyadirProductoCesta"
                               asp-route-idproducto="@Model.IdProducto"
                               class="btn w-100" style="background-color: #9acb8d;">
                                Añadir producto a carrito
                            </a>
                        }

                        @if (favoritos != null)
                        {
                            @if (!favoritos.Contains(@Model.IdProducto))
                            {
                                <a asp-controller="Tienda"
                                   asp-action="AnyadirProductoFavoritos"
                                   asp-route-idproducto="@Model.IdProducto"
                                   class="btn w-100" style="background-color: #9acb8d;">
                                    Añadir producto a favoritos
                                </a>
                            }
                            else
                            {
                                <button class="btn btn-secondary w-100">
                                    Producto ya en favoritos
                                </button>
                            }
                        }
                        else
                        {
                            <a asp-controller="Tienda"
                               asp-action="AnyadirProductoFavoritos"
                               asp-route-idproducto="@Model.IdProducto"
                               class="btn w-100" style="background-color: #9acb8d;">
                                Añadir producto a favoritos
                            </a>
                        }
                    }

                </div>
            </ul>
        </li>
    </ul>

    <div class="container mt-5" >
        <h2 style="font-weight: 600">Comentarios</h2>
        @if (comentarios.Count == 0)
        {
            <h2 class="text-danger" style="margin-top: 1em">No hay comentarios</h2>

        }
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-5">
            @foreach (Comentario com in comentarios)
            {
                <div class="col">
                    <div class="card shadow-sm" style="border-radius: 35px; margin-bottom:1rem">
                        <div class="card-body">
                            <h5 class="card-title">@com.IdComentario</h5>
                            <p class="card-text">@com.ComentarioTexto</p>
                            @for (int i = 0; i < 5; i++)
                            {
                                <span class="fa fa-star @(i < com.Valoracion ? "checked" : "")"></span>
                            }
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</body>

MvcTiendaPrueba/Views/Tienda/Favoritos.cshtml
@model List<Producto>

<head>
    <!-- Font Awesome Icon Library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/misestilos.css" asp-append-version="true" />

</head>

<a asp-controller="Tienda" asp-action="PaginarGrupoProductos" style="margin:auto">
    <span class="material-symbols-outlined" style="color: black; border: 1px solid black; border-radius: 20px;">
        arrow_back
    </span>
</a>

<body>


    @if (Model == null)
    {
        <h2 class="text-danger" style="text-align: center;">No hay favoritos</h2>
    }
    else
    {
        <div style="display: flex; align-items: center; justify-content: space-between;margin: 1px 20px 1px 20px;">
            <h3 class="text-primary mt-3">Productos en favoritos: @Model.Count()</h3>
        </div>

        <div class="container mt-5">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-1 g-2">
                @foreach (Producto pro in Model)
                {
                    <div class="col">
                        <div class="card shadow-sm" style="border-radius: 35px; margin-bottom:1rem;">
                            <div class="d-flex justify-content-between align-items-center card-body">
                                <img src="~/images/cenicero.png" style="width: 9%;margin-left: 30px;">
                                <div>
                                    <h4 class="card-title" style="font-weight: bold;">@pro.Nombre</h4>
                                    <p class="card-text">@pro.Descripcion</p>
                                </div>
                                <div class="ml-auto">
                                    <p style="font-weight: bold;">@pro.Precio €</p>
                                </div>
                                <div style="margin-right: 25px">
                                    <a asp-controller="Tienda" asp-action="EliminarProductoFavoritos"
                                       asp-route-idproducto="@pro.IdProducto" class="btn btn-danger">
                                        <span class="material-symbols-outlined">delete</span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    }

</body>


@section scripts {
    <script>

    </script>
}

MvcTiendaPrueba/Views/Tienda/Index.cshtml
@{
    ViewData["Title"] = "Inicio";
    Layout = null;
    var comentarios = ViewData["COMENTARIOS"] as List<Comentario>;
    var categorias = ViewData["CATEGORIAS"] as List<Categoria>;
    string? user = Context.Session.GetString("USUARIO");
    bool esAdmin = Context.Session.GetObject<bool>("EsAdmin");
}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mi Tienda Artesanal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/misestilos.css" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="~/css/slick.css" />
    <link rel="stylesheet" type="text/css" href="~/css/slick-theme.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css"  />
    <!-- Font Awesome Icon Library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />


    <style>

        html, body {
            height: 100%;
        }

        .main-container {
            min-height: calc(100% - 56px); /* Resta la altura de la barra de navegación */
            display: flex;
            flex-direction: column;
        }

        footer {
            margin-top: auto; /* Hace que el pie de página se pegue al final del contenedor */
        }

        .checked {
            color: orange;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <div>
                <a class="navbar-brand" asp-controller="Tienda" asp-action="Index">ResinCrafted</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="navbarResponsive" style="justify-content:end; padding-top: 10px">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Tienda" asp-action="Index">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Tienda" asp-action="PaginarGrupoProductos">Productos</a>
                    </li>
                    @if (Context.User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Tienda" asp-action="Cesta">Cesta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Tienda" asp-action="Favoritos">Favoritos</a>
                        </li>
                    }
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <span class="material-symbols-outlined">
                                person
                            </span>
                        </a>
                        <ul class="dropdown-menu">
                            @if (Context.User.Identity.IsAuthenticated)
                            {
                                <li>
                                    <a class="dropdown-item text-dark" asp-controller="Tienda" asp-action="PedidosUsuario">Mis pedidos</a>
                                </li>
                                <li>
                                    <a class="dropdown-item text-dark" asp-controller="Account" asp-action="MiPerfil">Mi perfil</a>
                                </li>
                                @if (esAdmin)
                                {
                                    <li >
                                        <a class="dropdown-item text-dark" asp-controller="Account" asp-action="PanelAdmin">Panel Admin</a>
                                    </li>
                                }
                                <li>
                                    <a class="dropdown-item text-dark" asp-controller="Account" asp-action="Logout">Log Out</a>
                                </li>
                            }
                            else
                            {
                                <li>
                                    <a class="dropdown-item text-dark" asp-controller="Account" asp-action="Login">Log In</a>
                                </li>
                                <li>
                                    <a class="dropdown-item text-dark" asp-controller="Account" asp-action="Register">Register</a>
                                </li>
                            }
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>


    <div class="multiple-items" style="width: 90%; display: flex; margin: auto;">
        <div><img src="~/images/bolis.jpeg" class="img-fluid rounded-start" alt="..."></div>
        <div><img src="~/images/llavero.jpeg" class="img-fluid rounded-start" alt="..."></div>
        <div><img src="~/images/joyas.jpg" class="img-fluid rounded-start" alt="..."></div>
        <div><img src="~/images/bolis.jpeg" class="img-fluid rounded-start" alt="..."></div>
        <div><img src="~/images/llavero.jpeg" class="img-fluid rounded-start" alt="..."></div>
        <div><img src="~/images/joyas.jpg" class="img-fluid rounded-start" alt="..."></div>
    </div>

    <section>
        <h2>Categorías</h2>

        <ul class="shop-pets">
            @foreach (Categoria cat in categorias)
            {
                <li class="card-large card-light" id="sup-dog">
                    <ul style="margin-top:20px; text-align:center">
                        @cat.Nombre
                        <div class="card-image"><img src="~/images/cenicero.png" style="border-radius: 1px 50px 1px 50px"></div>
                        <a asp-controller="Tienda" asp-action="ProductosCategoria" asp-route-idcategoria="@cat.IdCategoria" style="margin:auto"><button class="btn-outline-light">Ver productos</button></a>
                    </ul>
                </li>
            }

        </ul>
    </section>


    <!--<footer class="py-4 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Derechos de autor &copy; 2024 - Mi Tienda Artesanal</p>
        </div>
    </footer>-->

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></script>


        <script>

            $('.multiple-items').slick({
                infinite: true,
                slidesToShow: 3,
                slidesToScroll: 3,
                autoplay: true,
                autoplaySpeed: 2000,
            });
        

        </script>
    
    
</body>
</html>

MvcTiendaPrueba/Views/Tienda/PaginarGrupoProductos.cshtml
@model List<Producto>

@{
    ViewData["Title"] = "PaginarGrupoProductos";
    int registros = (int)ViewData["REGISTROS"];
    int numeroPagina = 1;
    int numeroPaginaActual = (int)ViewData["NumeroPaginaActual"];
    var categorias = ViewData["CATEGORIAS"] as List<Categoria>;
}
<head>
    <link rel="stylesheet" href="~/css/misestilos.css" asp-append-version="true" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tu título aquí</title>
    <style>

        .card-container {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
            padding: 20px;
        }

        .card {
            width: calc(24% - 20px); /* Ajustar el ancho según el número de elementos por fila */
            /*height: 350px; /* Ajustar la altura según sea necesario */
            height: auto;
            margin-bottom: 20px;
            padding: 20px;
            background-color: #ffffff;
            box-shadow: 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);
            text-align: center;
            min-width: 18em;
            max-width: 19em;
        }


        .pageTitle {
            font-size: 18px;
            color: #3a3a3a;
            margin: 10px 1px;
        }
        }

        .bottomCardTitle {
            font-size: 24px;
            color: #3a3a3a;
            margin-top: 20px;
            margin-bottom: 10px;
        }

        .bottomCardText {
            font-size: 14px;
            color: #9a9a9a;
            line-height: 1.5;
            margin: 0;
        }

        #IconRight, #backIconBottom {
            width: 20px;
            height: 20px;
            background: url(https://image.ibb.co/fV7eBy/icon1.png) no-repeat center;
            background-size: cover;
        }

        .card img {
            max-width: 70%;
            height: auto;
            margin-bottom: 10px
        }

        #sidebar {
            position: fixed;
            top: 0;
            left: 0;
            height: 100%;
            width: 250px;
            background-color: #343a40; /* Cambia el color de fondo del sidebar según tus preferencias */
            padding-top: 60px; /* Espacio superior para evitar que el contenido se superponga al header */
        }

            #sidebar .nav-link {
                color: #fff; /* Color del texto en el sidebar */
            }

        #content {
            margin-left: 250px; /* Ancho del sidebar */
            padding: 20px;
            margin-top: 60px; /* Ajusta el margen superior para evitar que se solape con el menú superior */
        }

        .active-pagination {
            background-color: #9acb8d;
        }

    </style>
</head>

<body>
    <div style="display:flex;margin: 20px 1px 20px 1px;">
        @foreach (Categoria cat in categorias)
        {
            <a asp-controller="Tienda" asp-action="ProductosCategoria" asp-route-idcategoria="@cat.IdCategoria" style="margin:auto;text-decoration:none"><button class="btn-outline-light" style="background-color: #9acb8d;">@cat.Nombre</button></a>
        }
    </div>

    <div class="card-container">
        @foreach (Producto pro in Model)
        {
            <div class="card">
                <div id="App">
                    <div id="Top">
                        <div id="titleBar">
                            <p class="pageTitle" style="font-weight: bold">@pro.Nombre</p>
                            <img src="https://twinsaccesorios.cl/wp-content/uploads/2022/08/IMG-4989-scaled.jpg" alt="Descripción de la imagen" width="80%">
                        </div>
                    </div>
                    <div id="Bottom">
                        <p class="bottomCardTitle" style="font-weight: bold">@pro.Precio €</p>

                        <a asp-controller="Tienda"
                           asp-action="DetailsProducto"
                           asp-route-idproducto="@pro.IdProducto" class="btn" style="margin-top:15px;background-color: #9acb8d;">
                            Ver más
                        </a>
                    </div>
                </div>
            </div>
        }
    </div>

    <div style="margin-bottom: 70px; display: flex; justify-content: center; align-items: center">
        <ul class="list-group list-group-horizontal">
            @for (int i = 1; i <= registros; i += 16)
            {
                <a asp-controller="Tienda"
                   asp-action="PaginarGrupoProductos"
                   asp-route-posicion="@i"
                   style="text-decoration:none">
                <li class="@(i == numeroPaginaActual ? "list-group-item active-pagination" : "list-group-item")"
                    style="@(i == numeroPaginaActual ? "" : "background-color: #a7d79a91;")">
                        @numeroPagina
                </li>
                </a>
                numeroPagina += 1;
            }
        </ul>
    </div>

</body>

MvcTiendaPrueba/Views/Tienda/PedidosUsuario.cshtml
@model List<DetallePedidoView>

    <head>
    <link rel="stylesheet" href="~/css/misestilos.css" asp-append-version="true" />

</head>

<body>

    @if (Model == null || Model.Count == 0)
    {
        <h2 class="text-danger" style="text-align: center;">No hay pedidos realizados</h2>
    }
    else
    {
        <h1>Pedidos realizados</h1>

        <div class="container mt-5">
            @foreach (var pedido in Model.GroupBy(p => p.IdPedido))
            {
                <div class="row mb-4">
                    <div class="col" style="background-color: #9acb8d">
                        <h3>Pedido @pedido.Key</h3>
                    </div>
                </div>
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-1 g-2">
                    @foreach (var detallePedido in pedido)
                    {
                        <div class="col">
                            <div class="card shadow-sm" style="border-radius: 35px; margin-bottom:1rem">
                                <div class="card-body">
                                    <h5 class="card-title">@detallePedido.NombreProducto</h5>
                                    <p class="card-text">@detallePedido.PrecioUnitario €</p>
                                    <p class="card-text" style="font-weight: bold">Total pedido: @detallePedido.TotalPedido €</p>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            }
        </div>
    }


</body>